### ISSUE TITLE
Feature Request: Implement development flag to bypass required rule parameters

### ISSUE THREAD

**Issue by josephbleroy** [morningconsult/go-elasticsearch-alerts#6]
I was wondering if it was possible to implemented a development flag so that certain configuration parameters can be bypassed? 

For example, the when the rule output is `email`, a username and password is required. In some development instances, we can bypass those settings via the SMTP server. 

If I do not fill in the `username` and `password` parameters, Go Elasticsearch Alerts throws an error since those fields are required. Is there any way to currently bypass this?

```
        {
            "type": "email",
            "config": {
                "host": "172.0.0.0",
                "port": 25,
                "from": "name@company.com",
                "to": "name@company.com",
                "username": "",
                "password": ""
            }
        },
```

Thank you!

**Comment by DDBellinghoven** [comment]
Absoultely - f19314780d4ada01eadbe518a84db2cb6023805a should take care of it

**Comment by josephbleroy** [comment]
Much appreciated! :+1:
