### ISSUE TITLE
Documentation page is missing.

### ISSUE THREAD

**Issue by tb-alpha9** [morningconsult/go-elasticsearch-alerts#99]
Hey everyone,

thank you for this great tool!

I just want to mention that the github page is gone: https://morningconsult.github.io/go-elasticsearch-alerts/

Regards,
Tobi

**Comment by alexdulin** [comment]
Thanks for letting us know about this. Not sure why the pages deployment disappeared, but it looks like reconfiguring it has worked. If you trying going to the documentation it should be back.

**Comment by tb-alpha9** [comment]
Thank you!
